apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: master-server-pod-creator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-creator
subjects:
- kind: ServiceAccount
  name: master-server
