apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "update", "patch", "get", "watch", "list", "delete"]
- apiGroups: [""]
  resources: ["podtemplates"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["daemonsets", "deployments"]
  verbs: ["create", "update", "patch", "get", "watch", "list", "delete"]
