apiVersion: v1
kind: Service
metadata:
  name: master-service
spec:
  selector:
    app: master-server
  ports:
  - name: master
    protocol: UDP
    port: 2000
    targetPort: master
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: mariadb
  ports:
  - name: mariadb
    protocol: TCP
    port: 3306
    targetPort: tcp-db-svc
