name: Cmake CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: cmake-configure
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'default'
    - name: cmake-build
      uses: lukka/run-cmake@v10
      with:
        buildPreset: 'default'
    - name: cmake-test
      uses: lukka/run-cmake@v10
      with:
        testPreset: 'default'
    - name: artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-build
        path: |
          build
          !build/CMakeCache.txt
          !build/build.ninja
          !build/_deps
          !build/cmake_install.cmake
          !build/*.a
