# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, closed-beta, crux-prime, dev ]
  pull_request:
    branches: [ master, closed-beta, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu-build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.3
        with:
          submodule_update: ON
          create_package: OFF
      - uses: actions/upload-artifact@v2
        with:
          name: MasterServer
          path: build/MasterServer
      - uses: actions/upload-artifact@v2
        with:
          name: WorldServer
          path: build/WorldServer
      - uses: actions/upload-artifact@v2
        with:
          name: ChatServer
          path: build/ChatServer
      - uses: actions/upload-artifact@v2
        with:
          name: AuthServer
          path: build/AuthServer
